POST http://localhost:8080/clientActions/v1/searchForProduct
Content-Type: application/json

{
    "keyword":"%Soins visage%",
    "state": false
}

#########################################

POST http://localhost:8080/clientActions/v1/searchForProductWithFilter
Content-Type: application/json

{
    "keyword":"%Soins visage%",
    "state": false,
    "fromRow": 0,
    "toRow":10,
    "fromPrice": 100,
    "toPrice": 900
}

##############################################
POST http://localhost:8080/clientActions/v1/getClientOrders
Content-Type:  application/json

{
    "state": "approved"
}

##############################################
POST http://localhost:8080/clientActions/v1/getClientInfo
Content-Type:  application/json


##############################################
POST http://localhost:8080/clientActions/v1/editClientInfo
Content-Type:  application/json

{
    "clientName": "New Salah 2",
    "clientLastName": "New bahadi",
    "clientEmail": "new@gmail.com",
    "clientPhone": "new06",
    "clientAdress": "New Address",
    "clientPassword": "",
    "clientCity": 13
}